name: esalerz
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.5
  http: ^1.1.0
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  uuid: ^4.1.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  simple_animations: ^5.0.2
  ionicons: ^0.2.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  country_picker: ^2.0.21
  flutter_bloc: ^8.1.3
  csc_picker: ^0.2.7
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: InterSans
    fonts:
      - asset: fonts/Intersans-bold.otf
      - asset: fonts/intersans-regular.otf

  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat_Bold.ttf
        weight: 700
      - asset: fonts/Montserrat_Regular.ttf
        weight: 400
      - asset: fonts/Montserrat_Italic.ttf
        style: italic
        weight: 400
